### ISSUE TITLE
[BUG] Undefined reference - jsonnet_unparse_jsonnet is declared in parser.h

### ISSUE THREAD

**Issue by ishaangandhi** [google/jsonnet#1012]
https://github.com/google/jsonnet/blob/master/core/parser.h#L41

This function is declared and, as far as I see, never, implemented. How do I use it?

**Comment by johnbartholomew** [comment]
Hi. Thanks for the report - it does indeed appear that this function is declared but not implemented.

I looks like the earlier `jsonnet_unparse_jsonnet` implementation was removed in 17c59acbfd455e42ab6bae0e5517157be4bf0b90 when the new formatting (pretty-printing) code was first added. The longer (but unimplemented) declaration was introduced in that commit, and has been untouched since then.

Anyway, this function was never part of the jsonnet library interface, so its existence or non-existence is not relevant for people using the library. If you're looking for the functionality for emitting formatted jsonnet code, you want the functions declared in the libjsonnet_fmt header: https://github.com/google/jsonnet/blob/master/include/libjsonnet_fmt.h
