### ISSUE TITLE
Migrate Jsonnet from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by mbrukman** [google/jsonnet#1121]
It looks like the Travis CI badge in the README is broken, and the URL it points to is asking for a sign-in: https://app.travis-ci.com/github/google/jsonnet which suggests that PRs in this project are no longer covered by Travis CI.

It would be good to migrate https://github.com/google/jsonnet/blob/master/.travis.yml config to GitHub Actions and update the build status badge accordingly.

**Comment by johnbartholomew** [comment]
In progress. I've set up a GitHub workflow that builds and runs tests (#1130).

Coverage / TODO:

- [x] Plain Makefile build & `make test`
- [x] CMakeLists build & CTest
- [ ] Python setup & test
- [ ] Bazel build (are there bazel specific tests? not sure)
- [ ] Clang format check (included in the workflow but disabled for now, because the code doesn't currently match clang-format's preferences)
- [x] Update the badge URL in the README.

The Travis workflow also included checking both Clang/LLVM and GCC, and it had a MacOS / XCode build.

Finally, the Travis workflow included generating a Linux binary build tarball. That seems unnecessary to me - I doubt anyone is using it since it looks like it was only generated for 4 releases (v0.14.0 to v0.17.0) and any Linux distro that provides a jsonnet package will no doubt be building from source rather than using a binary tarball.

**Comment by johnbartholomew** [comment]
I'll call this done. The GitHub workflow now covers building & running tests for the plain Makefile build, the CMake build, the Bazel build, and the Python module build, and the build status badge in the README points at the GitHub workflow status.

Auto-formatting / format checking is postponed for a bit as it's always a pain doing a big global reformat and isn't so relevant for this issue anyway as the Travis CI workflow didn't check code formatting anyway.

Things we have lost, which could possibly come back in the GitHub workflow in the future: Mac OS / XCode build, and building with clang (instead of gcc).

**Comment by sparkprime** [comment]
Great job

**Comment by mbrukman** [comment]
This is awesome!! Thank you, @johnbartholomew!! 🚀 

> Things we have lost, which could possibly come back in the GitHub workflow in the future: Mac OS / XCode build, and building with clang (instead of gcc).

No worries, this is easy to add in the future.
