### ISSUE TITLE
Jsonnet Style Guide

### ISSUE THREAD

**Issue by davidzchen** [google/jsonnet#118]
Since we have the reformatter, let's also write a style guide.

**Comment by fare** [comment]
Until we have an official well-written style guide, can we already get answers to questions such as:

1- What is the official indentation? (Looks like you use 4 spaces per indentation level, comma as terminator in multiline lists, etc.)

2- What is the official naming convention? (std uses camelCase for functions, but many examples use snake_case for functions and/or objects, whereas others use CamelCase for some data structures) Are there conventions for naming predicate functions? Higher-order functions?

3- What is the convention for documenting those functions?

I'm certainly forgetting a lot of points, but yes, even a misformatted incomplete draft or a comment on this thread would be better than no style guide at all.

**Comment by sparkprime** [comment]
In Lieu of an official Jsonnet style guide I would repurpose the parts of PEP8 that are appropriate.  Why PEP8?  Because much of Jsonnet is designed syntactically (and semantically) to be familiar to Python programmers.  May as well be familiar on the style front as well.

Of course a blind application of PEP8 would be no good, we have to use our common sense as well, knowing which rules to ignore and what new rules to have.  But I think it's a good start and a lot of it is re-usable.  E.g.:

4 char soft tabs, snake_case for everything except class names (OK we don't have classes but if you give a mixin a name it's pretty much a class)

For documenting functions, I would use a /** */ comment block like Javascript or Doxygen.  It's not that hard to implement real support for this, since the comments are preserved by the parser.  We have no concept of a Python docstring.

**Comment by fare** [comment]
PEP8 says 79 characters per line. In https://github.com/google/jsonnet/pull/111 you mention 100 characters per line. Can you clarify the official style guide with this respect?

**Comment by sparkprime** [comment]
I wouldn't interpret #111 as anything official :)

Go with PEP8, This means a lot of the Jsonnet in the repo is non-compliant but we are where we are.

Since you're looking into this in some detail, if you start accumulating a list of additions to PEP8 or things which are not reasonable then that

**Comment by sparkprime** [comment]
Now we have a formatter and a linter, I think the rules they enforce suffice for our purposes.  A more detailed style guide has been made available by databricks: https://github.com/databricks/jsonnet-style-guide

**Comment by seh** [comment]
Unfortunately, [the Databricks guide prescribes camel case](https://github.com/databricks/jsonnet-style-guide#variable-declaration) in lieu of [snake case](https://github.com/google/jsonnet/issues/118#issuecomment-245807063). Decisions, decisions...

**Comment by sparkprime** [comment]
I don't think we can mandate any style that doesn't have tool support.  But local variables are something that the formatting tool could conceivably rename.  It would have to make sure the new name is not already in scope, but that is not hard.  Fields on the other hand are generally not possible to automatically rename and a lot of the time we are beholden to 3rd party JSON formats anyway.
