### ISSUE TITLE
Repeated asserts are ignored?

### ISSUE THREAD

**Issue by benley** [google/jsonnet#181]
Is this expected behavior somehow?

```jsonnet
{
  assert true,
  assert false,  // This should fail, but it doesn't!
}
```

**Comment by benley** [comment]
For comparison, this works correctly and yields an `Assertion failed` error:

```jsonnet
assert true;
assert false;
null
```

**Comment by benley** [comment]
And this might be a parser bug?

```jsonnet
[
  assert true;
  assert false;
]
```
yields `Unexpected: "]" while parsing terminal`

If there is a value in the list after the last assert it parses correctly, but the repeated asserts are still ignored.

**Comment by sparkprime** [comment]
{ assert true, assert false }  is a bug

assert true; assert false; null is WAI

the last case is WAI as a parse error, because arrays do not have self or get extended, you don't get to put assert in them like you can with objects.  You can however use assert expressions within array elements or outside the array.

I will look into the first case...

**Comment by benley** [comment]
Cool - thanks for the explanation!

**Comment by sparkprime** [comment]
Note also #185 but that's more of an edge case.
