### ISSUE TITLE
Parsing a string to JSON

### ISSUE THREAD

**Issue by hausdorff** [google/jsonnet#321]
@jbeda was kicking around the idea (which I quite like) of having jq-style filters, which would look something like this:

```
cat foo.yaml | addMixin honeycomb.jsonnet  | kubectl apply -f ...
```

where `addMixin` turns `foo.yaml` into a JSON document, and honeycomb.jsonnet takes it as a parameter and embeds some sidecar.

In order for this to work, I think `honeycomb.jsonnet` would have to parse a string and turn it into JSON.

What is the recommended way to do this sort of thing? Native extensions?

**Comment by hausdorff** [comment]
(For those tuning in via email, I accidentally hit "comment" before I was done, so I think you need to come to the website to see the edited message.)

**Comment by ant31** [comment]
@hausdorff On my side, I am using with nativeExtension: 
https://github.com/coreos/kpm/blob/master/kpm/jsonnet/lib/kpm-utils.libjsonnet#L57
https://github.com/coreos/kpm/blob/master/kpm/template_filters.py#L156-L160

the extension:
```
  # Try to convert a Json or Yaml file
   loadObject(data):: (
      std.native("obj_loads")(std.toString(data))
   ),
```

example: 
(add a port to an existing k8s service definition in Yaml)
```
local kpm = import "kpm.libjsonnet";

{
 "redis-svc.json": kpm.loadObject(importstr "redis-svc.yaml") +
                   {spec+: {ports+: [{name: "injected-new-port", port: 5555}]}}
}
```

real world example:
https://github.com/stackanetes/stackanetes/blob/master/rabbitmq/manifest.jsonnet#L57
(import a jinja2 template as a yaml string, resolve the jinja2 (nativeExt `kpm.jinja2()`) and then load it to a jsonnet object (nativeExt `kpm.loadObject()`))

**Comment by sparkprime** [comment]
You can do most of this already but it's a bit ugly:

(Note that the input in this case is actually full Jsonnet, not just JSON).

```$ echo '{ "x": 3 }'  | jsonnet --tla-code-file input=/dev/stdin -e 'function(input) input + { y: self.x + 10 }'
{
   "x": 3,
   "y": 13
}
```

You still need some yaml2json utility and I don't think there's a standard one (probably because YAML doesn't actually fit into JSON in general).

You could also implement addMixin in Python or C++, link in libjsonnet and provide a `std.native("get_input")()`.  Then the implementation of that native function could do the YAML parsing (which is what ant31 does, except he also does Jinja interpretation on the YAML before parsing it).  In that case you invoke the interpreter to execute something like this:  

```
std.native("get_input")() + import "$1"
```

Finally, a more complex but general answer is to add support for "custom manifesters" that acts like a post-processor on the Jsonnet value generated by the execution of the program, and returns a string (the final output).  Currently, there are two built-in manifesters -- the JSON encoding one and the -S one (which is expects a string and just returns it).  You could imagine having one that applies your mixin and then does the standard JSON manifestation.  I remember there was a discussion about this a year ago and there were other use cases for such a thing.  This is obviously the most work though.

**Comment by alok87** [comment]
want to change namespace in `alok-pod.json` How to do that using jsonnet?
```{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "data": {
                "alok-pod.json": "{\n  \"namespace\": \"alok\",\n  \"editable\": true,\n}"
            }
        },
    ]
}```

**Comment by sbarzowski** [comment]
You can use std.parseJson and std.manifestJson (I think you need to use at least 0.12 for that). 

Something along the lines of the code below should work:
```
parsedAlokPod = std.parseJson(yourObject.items.data["alok-pod.json"]);
newAlokPod = std.manifestJson(parseAlokPod + {namespace: "alok"});
yourObject + { items +: { data +: {'alok-pod.json: newAlokPod}}}
```
(I didn't actually run it, so typos are to be expected)

@alok87 It's better to use Stack Overflow (with tag jsonnet) for "How do I" kind of questions. Issues are for suggested changes / suspected problems.

BTW @sparkprime this issue can probably be closed as `std.parseJson` solves the original use case, too (at least if you ignore the YAML part - but we have a more specific issue for that, #460).

**Comment by sbarzowski** [comment]
@alok87 btw I recommend getting the newest version when using parseJSON, because a bug related to that was just fixed.
