### ISSUE TITLE
proposal: generate binding for other programming languages using SWIG 

### ISSUE THREAD

**Issue by mqliang** [google/jsonnet#406]
Using [SWIG](http://www.swig.org/) to generate wrapper for other languages, thoughts?

**Comment by sbarzowski** [comment]
hmmm... I have never used it, but on the surface it makes sense. We have some sort of API for 8 languages, so it could make it easier.

Have you used it before? It's hard for me to estimate how much work it would be to maintain it. 

How natural does it feel in the target language? Do you still need to write a wrapper by hand on top of that for the api to feel right?

(BTW I believe that usually running a jsonnet command is better than using any bindings, but that's another discussion.)

**Comment by mqliang** [comment]
> Have you used it before? It's hard for me to estimate how much work it would be to maintain it.

Basically, we need maintain a "interface file", in which we define the constant, function, etc that you want to export(for jsonnet, I think only stuffs in libjsonne need to be exported?), and then use SWIG to generate share object and wrapper for other language. See a simple example here http://www.swig.org/tutorial.html

**Comment by sparkprime** [comment]
I do have some experience with swig while working at Google, and although I'm sure we've overcomplicated it like we overcomplicate everything, it wasn't a very positive experience.  Actually, it was terrible.  That's why I wrote manual Python bindings.  I don't think it's really very helpful to use swig because you just end up debugging the same problems, but with a layer of stuff in the way.
