### ISSUE TITLE
std.mergePatch can't merge over error values

### ISSUE THREAD

**Issue by benley** [google/jsonnet#414]
I was hoping that this would work:

```jsonnet
std.mergePatch(
  { a: error "nope" },
  { a: "ok" }
)
```

but unfortunately that results in a runtime error, because mergePatch has to check the type of each field, and `std.type(error "err")` is also a runtime error.

I think it would be possible to make the above example work by checking the type of the replacement value before considering the original value, and ignoring the original value unless the replacement is an object.  But it still wouldn't be possible to do this:

```jsonnet
std.mergePatch(
  { a: error "nope" },
  { a: { b: "ok" } }
)
```

So now I'm wondering:  Would it break the world to make `std.type(error "nope")` return `"error"` instead of an error?  Or as an alternative, what about adding a boolean stdlib function like `std.isError(x)`?

**Comment by benley** [comment]
also note, in the specific example cases above you could replace `std.mergePatch` the simple `+` operator and carry on, but my actual use case was more like

```jsonnet
std.mergePatch(
  { a: { b: { c: { d: error "nope" } } } },
  { a: { bb: [stuff], b: { c: { d: { stuff: [morestuff] } } } } }
)
```
... where mergePatch is needed.

**Comment by sparkprime** [comment]
To paraphrase the question: "I can't implement the laziness of mixin composition with std.mergePatch because it deeply evaluates both sides even if the RHS wins".  Two more examples:

```
std.mergePatch(
  { a: [1,2,3][10] },
  { a: "ok" }
)
```

```
std.mergePatch(
  { a: non_terminating_function() },
  { a: "ok" }
)
```

`std.isError(x)` is basically try / catch functionality, which would poke that whole discussion with a stick again.  It would be preferable if there was a different solution here.

`std.type(e)` where e is an error returning "error"... Seemingly you could implement `std.isError(e)` with that, so it would be opening the try / catch can of worms again.

Why is mergePatch needed here?  It is possible to do this:

```
  { a: { b: { c: { d: error "nope" } } } }
  +
  { a: { bb: ['stuff'], b: { c: { d: { stuff: ['morestuff'] } } } } }  # Imported from plain JSON

```

and get

```
{
   "a": {
      "b": {
         "c": {
            "d": {
               "stuff": [
                  "morestuff"
               ]
            }
         }
      },
      "bb": [
         "stuff"
      ]
   }
}
```

**Comment by sparkprime** [comment]
The problem I think is that with + you can choose between `{ x: error "hi" } + { x: { } }` and `{ x: error "hi" } + { x+: { } }` where the latter does not do what you want, however the std.mergePatch() essentially decides to use +: if the type of both sides is an object, and use : otherwise.  But unfortunately it needs to know if the type of the LHS is an object for that, and doing so when the LHS is not a computable function is impossible.  Even the simple std.isObject(e) call is not possible to implement if e does not terminate.

The fundamental problem here may be that taking std.mergePatch() (which is designed for operation on raw data) and using it in a context where the LHS is not a computable object.

For your case, maybe one of these options will help:
1) use a different error marker, so that the LHS is always computable.  Maybe a function?  Maybe we should have a special value that can be passed around but is not manifestable, specifically for this case where we always want something to be overidden.
2) Use + instead of std.mergePatch, since it forces you to statically know the structure of your data and is therefore less automatic

**Comment by sparkprime** [comment]
I don't understand the argument about tailstrict.  Here is the code:

```
    mergePatch(target, patch)::
        if std.type(patch) == "object" then
            local target_object =
                if std.type(target) == "object" then target else {};

            local target_fields =
                if std.type(target_object) == "object" then std.objectFields(target_object) else [];

            local null_fields = [k for k in std.objectFields(patch) if patch[k] == null];
            local both_fields = std.setUnion(target_fields, std.objectFields(patch));

            {
                [k]:
                    if !std.objectHas(patch, k) then
                        target_object[k]
                    else if !std.objectHas(target_object, k) then
                        std.mergePatch(null, patch[k]) tailstrict
                    else
                        std.mergePatch(target_object[k], patch[k]) tailstrict
                for k in std.setDiff(both_fields, null_fields)
            }
        else
            patch,
```

If `std.type(patch) == "object"` then `std.setDiff(both_fields, null_fields)` is evaulated, which forces `both_fields` which forces `target_fields` which forces `std.type(target_object)`.

**Comment by sparkprime** [comment]
I am more and more thinking that what you want to do is
```
local external = function() "A marker that causes an error if it reaches the manifestation stage."

std.mergePatch(
  { a: { b: { c: { d: external } } } },
  import "something.json",
)
```

**Comment by sbarzowski** [comment]
@sparkprime 
> I don't understand the argument about tailstrict.

This evaluates just fine as it is, `target` is never evaluated:
```
std.mergePatch(error "nope", "ok")
``` 

But in the original example it's wrapped in an object:
```
std.mergePatch(
  { a: error "nope" },
  { a: "ok" }
)
```
Both `target` and `patch` evaluate to objects without errors. But then the recursive call happens:
```
std.mergePatch(target_object[k], patch[k]) tailstrict
```
which is effectively:
```
std.mergePatch(error "nope", "ok") tailstrict
```
This forces both arguments, even though `patch` is not an object.

**Comment by sparkprime** [comment]
I see what you mean, but in his case it will be forced internally anyway, even if it is not forced in the tail call.

**Comment by sparkprime** [comment]
@benley Did the workaround work, can I close this?

**Comment by benley** [comment]
Yeah - sorry I never followed up on this one after the initial discussion.  I'm comfortable with implementing application error values at a higher level than the jsonnet `error` type.

**Comment by sparkprime** [comment]
No worries, I have added this to my list of "things that would easier if we could catch exceptions"
