### ISSUE TITLE
Max stack frames exceeded and slowness with lots of inheritance and dict comprehension

### ISSUE THREAD

**Issue by FRidh** [google/jsonnet#426]
I'm currently evaluating whether we can switch from an in-house language to `jsonnet`. In the data we have a lot of inheritance takes place. I wrote the following simple test which, for higher values of `n`, results in `RUNTIME ERROR: Max stack frames exceeded.`, and is unfortunately also slow.

I've generated `jsonnet` code with the following Python

```py

x0 = 100
n = 3

s = [ '{\n']
s += [ '    TC0: {{"x": [{}]}},\n'.format(x0) ] 
s += [ '    TC{}: self.TC{} + {{x+:[{}]}},\n'.format(x+1, str(x), str(x0+x*3)) for x in range(n) ]
s += ['}\n']
s = "".join(s)
```

This gives

```py
> print(s)
{
    TC0: {"x": [100]},
    TC1: self.TC0 + {x+:[100]},
    TC2: self.TC1 + {x+:[103]},
    TC3: self.TC2 + {x+:[106]},
}
```

and

```py
> print(jsonnet.evaluate_snippet("snippet", s))

{
   "TC0": {
      "x": [
         100
      ]
   },
   "TC1": {
      "x": [
         100,
         100
      ]
   },
   "TC2": {
      "x": [
         100,
         100,
         103
      ]
   },
   "TC3": {
      "x": [
         100,
         100,
         103,
         106
      ]
   }
}
```
For `n = 300`
```
> %timeit (jsonnet.evaluate_snippet("snippet", s))

3.25 s ± 181 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
This was in a relatively slow VM.

For `n = 3000` (or actually `n = 999`)

```
RUNTIME ERROR: Max stack frames exceeded.
	snippet:503:12-21	object <anonymous>
	snippet:504:12-21	object <anonymous>
	snippet:505:12-21	object <anonymous>
	snippet:506:12-21	object <anonymous>
	snippet:507:12-21	object <anonymous>
	snippet:508:12-21	object <anonymous>
	snippet:509:12-21	object <anonymous>
	snippet:510:12-21	object <anonymous>
	snippet:511:12-21	object <anonymous>
	snippet:512:12-21	object <anonymous>
	...
	snippet:994:12-21	object <anonymous>
	snippet:995:12-21	object <anonymous>
	snippet:996:12-21	object <anonymous>
	snippet:997:12-21	object <anonymous>
	snippet:998:12-21	object <anonymous>
	snippet:999:12-21	object <anonymous>
	snippet:1000:12-21	object <anonymous>
	snippet:1001:12-21	object <anonymous>
	snippet:1002:13-22	object <anonymous>
	During manifestation	
```

**Comment by sbarzowski** [comment]
Thanks for the report and the benchmark. 

The benchmark actually hits a bunch of known pain points. This program in jsonnet requires O(n^3) time and puts O(n) frames on stack.

1) Slowness
(Sidenote: `self.TCn + {x+:[100+3n]}` is equivalent to `self.TCn + {x: super.x + [100 + 3n]}` which in this case is equivalent to {x: self.TCn.x + [100 + 3n]}`)

It boils down to two things:
- Object fields are evaluated every time they are used. 
- Array concatenation takes time proportional to the sum of the lengths.
This means that during manifestation each field is evaluated separately, each evaluating all the previous fields and then concatenating all the arrays. So evaluation of one field takes O(n^2) time and the whole thing runs in O(n^3). 

2) Stack overflow
What happened there is expected. Jsonnet imposes a limit on the stack size to avoid recursion from eating all the memory. In your benchmark each field requires evaluation of all the previous ones, so that means putting n frames on stack. You can always change the stack size limit using `-s` option.

BTW for arbitrary deep tail recursion you can use `tailstrict` (the best currently available documentation is this thread https://github.com/google/jsonnet/issues/343). Or you can often avoid recursion completely by using stdlib functions to aggregate stuff.

**Comment by sbarzowski** [comment]
FYI there is some work going on to improve the performance (mostly in the context of [go-jsonnet](https://github.com/google/go-jsonnet).) This benchmark is definitely going to be helpful there. 

Addressing these issues is going to take quite a while, though.

**Comment by FRidh** [comment]
@sbarzowski thanks for the quick detailed explanation!

> Stack overflow

In practice we don't have to recurse this deep, so I'm not too worried about the stack overflow. Instead, we go much broader, having one `TC` inherit from multiple other `TC` at a time. 

> - Object fields are evaluated every time they are used.
> 
> This means that during manifestation each field is evaluated separately, each evaluating all the previous fields and then concatenating all the arrays.

Consider again
```jsonnet
{
    TC0: {"x": [100]},
    TC1: self.TC0 + {x+:[100]},
    TC2: self.TC1 + {x+:[103]},
    TC3: self.TC2 + {x+:[106]},
}
```
Does that mean that `TC1.x` is evaluated more than once? That is, in order to compute `TC2.x` it needs to compute `TC1.x` *again*, and the same with `TC3.x`?

**Comment by sbarzowski** [comment]
> Does that mean that TC1.x is evaluated more than once? That is, in order to compute TC2.x it needs to compute TC1.x again, and the same with TC3.x?

Yes exactly. In the snippet above TC3 is going to be evaluated one time (during its manifestation), TC2 two times (during its manifestation and when evaluating TC3), TC1 will be evaluated three times (during its manifestation, when evaluating TC2, and when evaluating TC2 for TC3) and TC0 will be evaluated four times. 

There are some reasons for this behavior and AFAIK it doesn't cause problems in practice that often. Still I find it unfortunate.

**Comment by FRidh** [comment]
> This benchmark is definitely going to be helpful there.

If you want to use the actual code, feel free to copy it.

> There are some reasons for this behavior and AFAIK it doesn't cause problems in practice that often. Still I find it unfortunate.

The same is done with Nix actually.

Well, I'll go write some more tests/benchmarks to see whether we can switch to jsonnet. Thanks again!

**Comment by sparkprime** [comment]
Thanks for sharing this with us, it's very helpful.  I'd love to see more benchmarks; the more realistic, the better!

The position we're in is that we know there are certain things that don't work very well, and we know ways of fixing them, but it's hard to prioritize because we don't know how they affect real applications.  It's not just a question of investing time in the right places but controlling the complexity of the implementation(s) as well.
