### ISSUE TITLE
Provide a way to discover what external variables jsonnet evaluation requires

### ISSUE THREAD

**Issue by ceridwen** [google/jsonnet#483]
This is another feature request that pertains to the use-cases I mention in #478.  I'm porting to jsonnet a very hacky implementation that uses $ in YAML files in a way that's similar but not equivalent to [JSON reference](https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html) to mark locations where identifiers need to be shared between different locations in JSON output.

```
spec:
  template:
    metadata:
      labels:
        $foo: None
---
spec:
  selector:
    $foo: None
```

External variables are a better way of doing the actual insertion of identifiers into JSON, but unfortunately, finding out what variables a given input requires is harder.  My current hacky implementation converts the YAML into Python objects and then calls a Python function that walks the resulting tree, checks for strings that match the pattern, and returns a list of variables.

I'd like a way to invoke jsonnet so that it would give a JSON list of the names for the external variables required to evaluate a given jsonnet file or string.  The kind of analysis that I'm doing on JSON would require the jsonnet AST, which isn't exposed.  A failsafe but fragile method would be to run jsonnet repeatedly, each time parsing the traceback to find the `undefined external variable: foo` line, adding that external variable for the next run, and continuing until it either hits a different error or executes successfully.  (This will work right up until the traceback format changes.).  The other option I can see, short of writing a full jsonnet parser myself, is to just look for the pattern `std.extVar(\w+)` in the input.  This will fail the moment I need to put an external variable declaration in an imported file, but so far I think I can avoid that.

**Comment by sbarzowski** [comment]
This is very easy to do with jsonnet AST. The Go implementation of jsonnet is probably easier to use for this purpose (https://github.com/google/go-jsonnet). AST is exposed, but unstable (no backwards compatibility guarantee).  It's a matter of writing a simple recursive function like this one https://github.com/google/go-jsonnet/blob/master/linter/find_variables.go#L56. 

One practical problem is that in `std.extVar('whatever'')`, `std` is an object like any other. Nothing prevents you from defining `local std = {extVar(x): 42}` or `local other_std = std`. So some false positives and false negatives are expected. But for the purpose you described it should be ok, I guess.

**Comment by ceridwen** [comment]
I'm working in Python, so the Go implementation doesn't help me unless there are bindings for it.  (Are there?  I didn't see anything in the documentation about that.).  If there's an equivalent in the C++ library, I could look into ctypes or CFFI.

Yeah, in my use-case I can simply require that the jsonnet code I'm using doesn't redefine the standard library in either of those ways.

**Comment by sbarzowski** [comment]
@ceridwen Maybe you can make it a standalone command (a separate binary) and just run it as a command (`subprocess.call` or sth) . That's how I would do it. This way it could also be useful for others, even if they don't use Python.

In principle you could do the same thing with C++ version, but it would require exposing the AST and if you intend to do the actual work in Python, using AST over C interface is going to be painful.

BTW the bindings

**Comment by sparkprime** [comment]
The static analysis you're talking about isn't possible in general, because the parameter of std.extVar() can be computed, not all std.extVar() may be reachable, and there are more ways of getting at std.extVar than with the literal code std.extVar(), since std can be rebound and so on.

Can't you just leave a placeholder in the string of the generated JSON, then post-process it with something?

**Comment by sparkprime** [comment]
Besides the method of executing it satisfying each requested variable until it completes without error, (which is problematic because it won't find variables in unreachable code, and it's not guaranteed that Jsonnet will terminate quickly or at all), I don't think there's a way of doing what you want.  Any program analysis method is going to either miss them or find lots of things that aren't actually needed (due to not knowing whether some function call is a call to std.extVar or something else).

In your case you can probably hack something up for the code you're working with, but I don't think there's anything we can do centrally here.
