### ISSUE TITLE
How to detect if import stuff is exist?

### ISSUE THREAD

**Issue by lqj679ssn** [google/jsonnet#506]
Hi, I'm dealing with [kubeflow issue](https://github.com/kubeflow/kubeflow/pull/688).
Now I want to send a param `modelStorageType` through cmd. But this param has a default value. So I can also choose to not send this param through cmd (and get the default value `cloud`).

The code to deal with the param is 
`local modelStorageType = import "param://model_storage_type"`.

Anyone can tell me how to detect if `model_storage_type` is sent from cmd?

**Comment by sbarzowski** [comment]
This seems to be an issue of [ksonnet](https://github.com/ksonnet/ksonnet) rather than pure jsonnet.  You are more likely to get a complete answer on ksonnet slack channel or by opening an issue for ksonnet repo.

One thing that may be helpful to note is that `import` is just an expression in jsonnet which returns the result. There is no other metadata and no side-effects to import. So the only thing that matters is the value returned by`import "param://model_storage_type"` - there's just nothing else to look at.

It also means it's possible to do things like `if import "param://model_storage_type" == null then ...` or pass it directly to a function `foo(import 'bar.jsonnet')`. 

FYI currently I know very little about ksonnet. It's possible that ksonnet provides some metadata about available parameters, but it probably doesn't matter if you actually import them, the metadata sits there anyway.

**Comment by lqj679ssn** [comment]
ok thanks for replying!!

**Comment by lqj679ssn** [comment]
@sbarzowski I tried `if import "param://model_storage_type" == null` but failed, anyway thanks! now I've opened a [ksonnet issue](https://github.com/ksonnet/ksonnet/issues/489)
