### ISSUE TITLE
No tab indent for `jsonnet fmt`

### ISSUE THREAD

**Issue by marak8** [google/jsonnet#523]
Via `jsonnet fmt` command, it's possible to re-indent files with spaces and control the number of leading spaces with `-n` option. But it's not possible to re-indent via tabs.

**Comment by sparkprime** [comment]
Hard tabs are deliberately not supported since the formatter is opinionated. It will understand them and convert them, but not emit them.  The amount of indentation is stored in the AST as an int representing the number of spaces.  Supporting mixed or hard tab indentation would make that substantially more complicated.  As a data point, YAML does not support tabs.  My personal opinion is that hard tabs are bad because their width is non-standard and that makes it impossible to keep specific width limits.

**Comment by marak8** [comment]
That is sad to hear but I understand it. I wanted to mainly use it to reformat the file from the Vim editor, since the jsonnet syntax file does weird things. But me and my team also have preferred style (tabs) and we're reluctant to change that. I'm glad you left the issue open as I conclude that means you're open to apply patch that will let the other side of Tabs vs. Spaces war pick their style. :-)
