### ISSUE TITLE
jsonnet fmt `if ! foo` -> `if !foo`, which fails.

### ISSUE THREAD

**Issue by tomwilkie** [google/jsonnet#572]
If I run `jsonnet fmt` (0.11.2) on https://github.com/grafana/jsonnet-libs I get:

```diff
diff --git a/prometheus-ksonnet/lib/prometheus.libsonnet b/prometheus-ksonnet/lib/prometheus.libsonnet
index cf0571b..115325e 100644
--- a/prometheus-ksonnet/lib/prometheus.libsonnet
+++ b/prometheus-ksonnet/lib/prometheus.libsonnet
@@ -65,7 +65,7 @@
   local pvc = $.core.v1.persistentVolumeClaim,
 
   prometheus_pvc::
-    if ! $._config.stateful
+    if !$._config.stateful
     then {}
     else (
       pvc.new() +
@@ -78,7 +78,7 @@
   local volumeMount = $.core.v1.volumeMount,
 
   prometheus_statefulset:
-    if ! $._config.stateful
+    if !$._config.stateful
     then {}
     else (
       statefulset.new('prometheus', 1, [
```

Which fails when used with ks 0.8 `Not a unary operator: !$`.  Is the jsonnet version mismatch the source of the problem?

**Comment by sbarzowski** [comment]
Thanks for reporting. It's a lexer bug. `!$` should be parsed the same as `! $`.

It was reported and fixed in C++ version, but it seems we have exactly the same problem in go-jsonnet which I believe ks uses. Here's the original bug #503.

The quick solution is to add parentheses, like `!($._config.stateful)`. The real solution is to fix the lexer in go-jsonnet and update ks to use that.

**Comment by sparkprime** [comment]
This should be good now I think
