### ISSUE TITLE
Guidance on how to generate YAML stream sub to multi file layout.

### ISSUE THREAD

**Issue by josdotso** [google/jsonnet#637]
The general idea:
```
{
  'stream.yaml': [],
  'normal.json`: {},
}
```
Is this possible? I tried using the stdlib functions for YAML and YAML stream, but output ends up with a lot of `\n` chars to `stream.yaml`.

**Comment by josdotso** [comment]
related: https://github.com/kubernetes/kubeadm/issues/1502

**Comment by sbarzowski** [comment]
The reason you get `\n` in the output is that `std.manifestYamlDoc` and similar functions simply return string. Jsonnet applies then default manifestation to JSON on the result. So you get "double escaping". 

To output multiple files, some as JSON some as YAML you can use stdlib library and pass "raw string" option, so that automatic JSON manifestation is not applied. Take a look at the example below.

files.jsonnet:
```
{'foo.json': std.manifestJson({bar: 'a'}), 'some.yaml': std.manifestYamlDoc({something: ['a', 'b', 'c']})}
```
command to run:
```
jsonnet -e files.jsonnet -m . -S
```

Of course you are not limited to `std.manifestJson ` and other standard functions - any string producing function will do, so you can output any format (when you write or find an appropriate function, but the point is there is nothing special about `std.manifestJson`).

**Comment by josdotso** [comment]
Thanks for the help, @sbarzowski!  I'll give this a try and report back.

**Comment by josdotso** [comment]
I ended up using `std.manifestYamlStream(value)`  as the function, which worked perfectly.

This is so awesome!  Thanks again!
