### ISSUE TITLE
Impossible to get string with single backslash in output

### ISSUE THREAD

**Issue by alikhil** [google/jsonnet#679]
I am using jsonnet to write configurations for [drone ci](https://drone.io). Drone uses jsonnet to generate yaml file and use it as instruction for CI/CD.

For my needs I want to have the following output:

```json
{ "some-field" : "${DRONE_BRANCH/\//-}" }
```

I tried the following jsonnet script:
```json
{
  "some-field": "${DRONE_BRANCH/\//-}",
}
```
And it gave me:
```json
{
   "some-field": "${DRONE_BRANCH///-}"
}
```

Then I tried:
```json
{
   "some-field": "${DRONE_BRANCH/\\//-}"
}
```

It gave me:
```json
{
   "some-field": "${DRONE_BRANCH/\\//-}"
}
```

I did not find a way to achieve what I want. Seems to me it's currently impossible.

P.S. I am using the latest version of jsonnet 
```bash
$ jsonnet -v
Jsonnet commandline interpreter v0.13.0
```

**Comment by Raiondesu** [comment]
+10 for this. How come single slashes are not allowed in a JSON?\
This is ridiculous.

**Comment by sbarzowski** [comment]
The thing is that in JSON `"/"` and `"\/"` are equivalent, i.e. they describe the same sequence of characters (i.e. a single character U+002F). If I'm interpreting the JSON specification correctly, every compliant implementation should treat them the same per [RFC 7159 8.3 String Comparison](https://tools.ietf.org/html/rfc7159#section-8.3). 

Similarly JSON strings `"${DRONE_BRANCH/\//-}"` and `"${DRONE_BRANCH///-}"` refer to exactly the same sequence of characters `${DRONE_BRANCH///-}`. If you want a JSON string which denotes a string with a backslash there (e.g. because you feed it to a script which requires an escaped slash there), you should actually escape the backslash.  So if you want a JSON meaning `${DRONE_BRANCH/\//-}`, the right JSON is `"${DRONE_BRANCH/\\//-}`. 

Python agrees btw: 
```
>>> json.dumps(json.loads('"${DRONE_BRANCH/\\//-}"')) # double escaping
'"${DRONE_BRANCH///-}"'
>>> x = '"${DRONE_BRANCH/\\//-}"' # double escaping
>>> print(x)
"${DRONE_BRANCH/\//-}"
>>> print(json.loads(x))
${DRONE_BRANCH///-}
>>> x = '"${DRONE_BRANCH/\\\\//-}"' # double escaping
>>> print(x)
"${DRONE_BRANCH/\\//-}"
>>> print(json.loads(x))
${DRONE_BRANCH/\//-}
```

Escaping `/` is unnecessary, so Jsonnet doesn't put it there. Jsonnet generally goes for minimally escaped strings in the output. 

Please let me know if that answers your question.

**Comment by Raiondesu** [comment]
@sbarzowski, though it's a comprehensive answer, I suggest you read the question more... accurately.

>Then I tried:
>
>```
>{
>   "some-field": "${DRONE_BRANCH/\\//-}"
>}
>```
>It gave me:
>
>```
>{
>   "some-field": "${DRONE_BRANCH/\\//-}"
>}
>```

In other words, escaping the escaping backslash just produces two backslashes.

**Comment by sbarzowski** [comment]
> Complete mystification.

Please don't accuse me of bad intentions, when I'm trying to help you.

> Instead, it actually produces

Did you actually run it in Python? This was directly copy&pasted from Python shell. Here you can see it yourself: https://www.onlinegdb.com/S1g978ilH. 

> In other words, escaping the escaping backslash just produces two backslashes.

Yes, because it also needs to be escaped in the output JSON. I'm arguing that it is the correct behavior. And that trying to get JSON output `{ "some-field" : "${DRONE_BRANCH/\//-}" }` specifically and not `{ "some-field" : "${DRONE_BRANCH///-}" }` is probably a wrong goal, because these two are equivalent. These two JSONs mean exactly the same thing, so why would you prefer the one with unnecessary escaping?

For completeness I'll add that you can use the "raw string" mode (`-S` option) to do your own serialization if you really want to. Then your program must produce a string, which will be printed without any additional escaping. But as long as your output is standard JSON you shouldn't have to.

**Comment by sbarzowski** [comment]
In other words if you want it to be loaded with a **single** backslash you need these **two** backslashes in JSON.

E.g.: 
```
➜ jsonnet -e '{
   "some-field": "${DRONE_BRANCH/\\//-}"
}' | python -c 'import json; import sys; print(json.load(sys.stdin)["some-field"])'
${DRONE_BRANCH/\//-}
```

With a single backslash it won't work as expected (it will be interpreted as escaped `/` which is just `/`):
```
➜ cat foo.json
{ "some-field" : "${DRONE_BRANCH/\//-}" }
➜ cat foo.json | python -c 'import json; import sys; print(json.load(sys.stdin)["some-field"])'
${DRONE_BRANCH///-}
```

**Comment by sbarzowski** [comment]
I'm going to assume that it's all clear now after my last explanation. If it's not, feel free to reopen.

**Comment by sparkprime** [comment]
Just came here to add that in YAML, you can specify a single character string containing a backslash as either:
```yaml
\
```

or

```json
"\\"
```

In JSON, only the latter is supported.  When Jsonnet generates YAML with `std.manifestYAMLDoc`, it chooses to emit YAML in the second form, because implementing that is simpler, and it's equivalent.  Drone CI should interpret `"\\"` in the way that you want.

**Comment by sparkprime** [comment]
Oh and just for completeness -- the various ways of specifying it in Jsonnet:
```jsonnet
[
  "\\",
  '\\',
  @"\",
  @'\',
  // Note, this last one also adds a \n, see #289
  |||
    \
  |||,
]
```
