### ISSUE TITLE
Code formating for Prettier

### ISSUE THREAD

**Issue by limitlessloop** [google/jsonnet#681]
Hello,

Is there any way to support formatting with Prettier for jsonnet files? I noticed this issue https://github.com/google/jsonnet/issues/73 talking about a formatting tool but I'm unfamiliar with go fmt. Could it be ported to Prettier?

Many thanks

**Comment by sbarzowski** [comment]
There exists an official formatting tool called `jsonnetfmt`. It should be pretty straightforward to use.

Regarding Prettier, I'm not familiar with it. If it can act as a simple facade to our official tool, then why not (not sure if possible/consistent with how Prettier is supposed to be used).

**Comment by limitlessloop** [comment]
Ok thanks, is `jsonnet fmt` a CLI tool only? I'm looking for support for VScode. I've seen there is a VScode extension, but when I tried it, it didn't work. I've have `jsonnet` installed and in my PATH but no luck. Support for Prettier would be useful, but I'm not sure how much of a demand there would be for it.

**Comment by sbarzowski** [comment]
`jsonnetfmt` is a separate command since 0.13 and it generally should be distributed together with `jsonnet`.

I have never used it with an editor integration, but it should be quite trivial. Even without an extension you can set up a "task" in VS Code which just runs the command. The `autopep8` example from [the vs code tasks tutorial](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution) should be easy to adapt for jsonnetfmt.

Of course an extension would be more convenient. The existing (3rd party) VS Code extension has some pretty advanced features (like very smart autocompletion), but is quite out of date (perhaps a simpler extension which just runs official tools should be created and that would be easier to keep up to date).

**Comment by sbarzowski** [comment]
We want to focus on jsonnetfmt I think and use it as the source of truth (and all editors should use it for autoformatting Jsonnet). Closing this. 

If anyone has trouble using jsonnetfmt for their formatting needs, feel free to open an issue.
