### ISSUE TITLE
`jsonnetfmt -i` always changes the file timestamp even for unchanged files

### ISSUE THREAD

**Issue by dcwangmit01** [google/jsonnet#702]
`jsonnetfmt -i` always changes the file timestamp even for unchanged files

This makes it difficult for Makefile to always run jsonnet format, while ensuring that other targets are made only when files have been reformatted.

```
$ md5sum context.jsonnet
93fae8a13b4f4aa13d0747cc16b2d43d  context.jsonnet
$ ls -la context.jsonnet
-rw-r--r-- 1 vagrant vagrant 9962 Aug 22 16:43 context.jsonnet
$ date
Thu Aug 22 16:45:51 UTC 2019
$ jsonnetfmt -i context.jsonnet
$ ls -la context.jsonnet
-rw-r--r-- 1 vagrant vagrant 9962 Aug 22 16:46 context.jsonnet
$ md5sum context.jsonnet
93fae8a13b4f4aa13d0747cc16b2d43d  context.jsonnet
```

**Comment by sbarzowski** [comment]
Right, I agree. We could see if the old file text is any different from the new one before writing in to the file.

BTW I vaguely recall this coming up before, but I can't find the issue. Anyway it should be quite easy to do. It should be enough to check that the input is actually different from the output here:
https://github.com/google/jsonnet/blob/master/cmd/jsonnetfmt.cpp#L276

Right now I'm in the middle of other changes, so feel free to make it your first PR 😃. Otherwise we'll probably get to it sooner or later (and in such case feel free to ping us here, if it seems we forgot).

**Comment by dcwangmit01** [comment]
@sbarzowski  Thanks for the hints.  I'd like to do the PR.  Give me 2 weeks to get to it please.

**Comment by dcwangmit01** [comment]
@sbarzowski https://github.com/google/jsonnet/pull/704

I found some time on a plane.  My first PR from over the pacific :)
