### ISSUE TITLE
yaml2jsonnet utility

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#765]
It would be nice to have a tool which allows converting existing YAML files to equivalent (trivial) Jsonnet. It doesn't need to support the whole YAML (a reasonable subset would still be useful), but it should preserve comments and ordering. This could be very useful when working with some existing YAML-based setup to gradually introduce Jsonnet.

I imagine that would be a completely separate binary. It may be a separate project or part of the standard Jsonnet distribution (both ways make sense for me).

**Comment by sbarzowski** [comment]
BTW for those who don't care about comments and order that's pretty trivial - it's enough to convert YAML to JSON and the JSON is also a valid Jsonnet program.

**Comment by alxarch** [comment]
I took a stab at sth like this last year, have a look at [ycat](https://github.com/alxarch/ycat)

**Comment by sbarzowski** [comment]
Hey, this is a pretty cool tool! it seems to me more like "jq but using Jsonnet"  than a conversion tool, though.

The main point for this issue is to have a way of converting the YAML files while preserving the comments and the order, so that for example a Kubernetes user who wrote YAML by hand can trivially migrate (while preserving the comments and the reasonable order of fields).

**Comment by waisbrot** [comment]
I was writing some Kubernetes resources for myself in Jsonnet and enjoying the experience -- I get a good understanding of what all the resources are and how they fit together. It's also nice because you can mostly just keep `kubectl apply`ing the output of `jsonnet -y` over and over.

Then I grabbed some Helm charts and was frustrated that (1) I'd like to really learn what's going on in these complex charts also and (2) for my toy setup Helm's notion of immutable releases is really inconvenient.

Anyway, I made https://github.com/waisbrot/yaml2jsonnet and was able to transform the nginx-ingress chart into a Jsonnet doc that worked in Kubernetes. It's pretty crude code right now, but if anyone has a use-case that they want me to try I'd be happy to give it a whirl.

**Comment by sbarzowski** [comment]
Nice! I haven't tried it yet, but based reading the code, it looks like it solves the problem here.

@josdotso, @rustycl0ck, @mpeters FYI
