### ISSUE TITLE
Importing external YAML files

### ISSUE THREAD

**Issue by alexec** [google/jsonnet#790]
I'm currently using JK to template manifests, but I'd like to know if I can do the same thing with Jsonnet instead.

The manifests basically loop over the contents on an array stored in a YAML file.

Can you tell me how to read that YAML file from disk please?

I can't find this use case in the docs.

**Comment by sparkprime** [comment]
YAML has many incompatible implementations which is why it was never included.  There is an incomplete effort to add std.parseYaml() to go-jsonnet which uses the Go YAML implementation which people think is pretty decent. https://github.com/google/go-jsonnet/pull/339

However why use YAML for your list instead of JSON or (if you need it) Jsonnet?  Then you can just use `import`.  If you do need to use YAML for some reason, you could always convert it using a 3rd party tool into JSON and then use jsonnetfmt to turn it into Jsonnet (there is even a page on the website that will do that for Kubernetes manifests).

**Comment by sbarzowski** [comment]
For completeness: you can import any file with `importstr`. But then you probably need to parse it, and we don't currently have a YAML parser. The best way is to preprocess the file before feeding it to Jsonnet.

**Comment by alexec** [comment]
I could easily use JSON - is that possible?

**Comment by sparkprime** [comment]
Yes, JSON is a subset of Jsonnet, so import it like Jsonnet.

**Comment by alexec** [comment]
simple
```
local clusters = import 'data/cluster-configs.json';
std.map(function(c) {
     name:c.name
},clusters)
```

maybe docs could be better on this topic?

**Comment by sparkprime** [comment]
The tutorial does mention it:
```
