### ISSUE TITLE
toJson but without newlines

### ISSUE THREAD

**Issue by ghostsquad** [google/jsonnet#796]
Any idea if there's a way to take an object and convert it to a JSON string but without newlines?

**Comment by sbarzowski** [comment]
There is no stdlib function which does that directly, but it's very easy:
```
local manifestJsonSingleLine(val) = std.strReplace(std.manifestJson(val), "\n", " ")
```
Simple replacement works, because JSON spec requires all control characters (incl. newlines) to be escaped in strings.
> All Unicode characters may be placed within the
   quotation marks, except for the characters that MUST be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).
(https://tools.ietf.org/html/rfc8259)

You can also write your own custom manifester and have total freedom in how it is formatted. It is really easy, the one for JSON has 37 lines and no magic going on (https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L902).

**Comment by ghostsquad** [comment]
good to know! thanks!
