### ISSUE TITLE
Weird behavior of + between if expressions

### ISSUE THREAD

**Issue by mbarbero** [google/jsonnet#822]
With Jsonnet commandline interpreter v0.16.0 (tested with 0.15.0 as well)

```jsonnet
local firstIf = true;
local secondIf = true;
{} 
+ 
if (firstIf) then {
  first: "foo",
} else {
  first: "bar",
}
+
if (secondIf) then {
  second: "fuu",
} else {
  second: "buu",
}
```

gives 

```json 
{
   "first": "foo"
}
```

while I would expect 

```json
{
   "first": "foo",
   "second": "fuu"
}
```

When I add parenthesis around the if expressions:

```jsonnet
local firstIf = true;
local secondIf = true;
{} 
+ 
(if (firstIf) then {
  first: "foo",
} else {
  first: "bar",
})
+
(if (secondIf) then {
  second: "fuu",
} else {
  second: "buu",
})
```

Jsonnet properly outputs my expectation

```json
{
   "first": "foo",
   "second": "fuu"
}
```

Am I misunderstanding a rule or is it a bug?

**Comment by sbarzowski** [comment]
There is no bug. It is just that `else` binds weaker than `+`. This is intentional, otherwise you would get more confusing behavior:
```
if true then 2 else 2 + 2
```
It is equivalent to:
```
if true then (2) else (2 + 2)
```
If `else` was stronger that `+` then it would be equivalent to:
```
(if true then 2 else 2) + 2
```
But fortunately it isn't, because that would get in the way much more often.

It is obvious when you run your program through `jsonnetfmt`:
```
local firstIf = true;
local secondIf = true;
{}
+
if (firstIf) then {
  first: 'foo',
} else {
         first: 'bar',
       }
       +
       if (secondIf) then {
         second: 'fuu',
       } else {
         second: 'buu',
       }
```

My recommendation is to always wrap complex expression in parentheses when they occur inside a chain like this. This is more explicit and readable, and you don't need to worry about where the `else` ends.

```
local firstIf = true;
local secondIf = true;
{}
+
(
  if (firstIf) then {
    first: 'foo',
  } else {
    first: 'bar',
  }
)
+
(
  if (secondIf) then {
    second: 'fuu',
  } else {
    second: 'buu',
  }
)
```

**Comment by mbarbero** [comment]
Thanks for the education with the detailed explanation, it makes perfect sense.
