### ISSUE TITLE
String formatting of floats gives incorrect value when rounding up fractions to wholes

### ISSUE THREAD

**Issue by benk-gc** [google/jsonnet#879]
When I format a float with `%.1f` I would expect the behaviour to be the same as in Python. For example, in Python:

```python
>>> '%.1f' % 0.95555
'1.0'
```

```python3
>>> '{:.1f}'.format(0.95555)
'1.0'
```

However, when the number would be '1.0', running this in jsonnet I get:

```
> jsonnet <(echo "'%.1f' % 0.95555") 
"0.10"
```

This happens when rounding up to other whole numbers too:

```
jsonnet <(echo "'%.1f' % 1.95555") 
"1.10"
```

Values where this would result in a number below one seem fine:

```
> jsonnet <(echo "'%.1f' % 0.85555") 
"0.9"
```

Values with more than one decimal place also seem fine:

```
> jsonnet <(echo "'%.2f' % 0.95555") 
"0.96"
```

**Comment by sbarzowski** [comment]
Oh, this is a serious bug. We need to fix it quickly. Thanks a lot for reporting!

**Comment by sbarzowski** [comment]
Ok, I know what's going on. The formatting code doesn't allow the fractional part to carry over to the wholes. 

So, for example this is also problematic: '%.4f' % 0.99995, because the fractional part rounds up to 1 and instead of producing 1, we produce 0.10000.

Here's the problematic part https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet#L557.
